### ISSUE TITLE
mimic joints in urdf

### ISSUE THREAD

**Issue by supsensei** [uwgraphics/relaxed_ik#7]
Hi again -

Working with a URDF that has mimic joints in the chain. I have found I need to explicitly call these out in the chains in the joint names and ordering lists to get all to work. The URDF viewer can recognize the mimic joints, but relaxed_IK process them as independent joints and does use the mimic constraint in the urdf. Any thoughts how to modify relaxed_IK to account for mimic joints?

Thanks.

**Comment by djrakita** [comment]
Hi,
This is a good point.  Mimic joints are not handled well by the solver at this point, but it would be worth adding support for that.  

Because mimic joints are not DOFs, I think the easiest way to handle this would just be as a post-process, i.e. at each update, all mimic joints are updated based on their own multipliers, offsets, and parent joint.  I'll add this to the list of things to add in, thanks for bringing it up!

**Comment by supsensei** [comment]
Thanks for the thoughts and keep it up.
